# Generated by Django 4.2 on 2023-04-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='template',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='template',
        ),
        migrations.AddField(
            model_name='notifytype',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.template', verbose_name='Шаблон'),
        ),
    ]
