# Generated by Django 4.2 on 2023-04-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(verbose_name='Тип уведомления')),
                ('slug', models.CharField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название шаблона')),
                ('html', models.TextField(null=True, verbose_name='HTML шаблон')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='Контент')),
                ('status', models.CharField(choices=[('WA', 'Ожидает отправки'), ('SE', 'Отправляется'), ('SD', 'Отправлено'), ('ER', 'Ошибка отправки')], max_length=2, null=True, verbose_name='Статус')),
                ('error_text', models.TextField(verbose_name='Текст ошибки отправки')),
                ('notify_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.notifytype', verbose_name='Тип уведомления')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название рассылки')),
                ('period', models.CharField(choices=[('OW', 'Раз в неделю'), ('OM', 'Раз в месяц')], max_length=2, null=True, verbose_name='Переодичность рассылки')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='Следующая рассылка')),
                ('notify_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.notifytype', verbose_name='Тип уведомления')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
