# Generated by Django 4.2 on 2023-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_remove_mailing_template_remove_notify_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytype',
            name='group',
            field=models.BooleanField(default=False, verbose_name='Групповое событие'),
        ),
    ]
