# Generated by Django 4.2 on 2023-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_notify_next_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytype',
            name='auth_group',
            field=models.CharField(blank=True, help_text='Оставьте это поле пустым, если рассылка для всех пользователей', max_length=255, null=True, verbose_name='Слаг группы пользователей'),
        ),
    ]
