name: Check pull requests

on:
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create folder for reports
        run: |
          mkdir -p lint_report/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-html mypy lxml

      - name: Check types with mypy
        id: mypy
        run: |
          mypy . --html-report lint_report/mypy/ || true

      - name: Lint with flake8
        id: flake
        run: |
          flake8 --select=E9,F63,F7,F82 .
          flake8 --exit-zero --format=html --htmldir=lint_report/flake8/ .

      - name: Load lint report
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: lint_report
          path: lint_report/

  send_message:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: send message
        if: ${{ steps.flake.result == 'success' }} and ${{ steps.mypy.result == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ TELEGRAM_CHAT_ID }}
          token: ${{ TELEGRAM_BOT_ID }}
          args: ${{ github.repository }} commit ${{ github.sha }} finished with successfully

      - name: Notify Failure In Telegram Channel
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          args: ${{ github.repository }} commit ${{ github.sha }} finished with error. ${{ steps.flake.outcome }} and ${{ steps.mypy.outcome }}